services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis